version: 3
workdir: .
allow:
  depOnAnyVendor: true
excludeFiles:
  - "^.*_test\\.go$"

components:
  main: { in: cmd/insight }
  config: { in: cmd/insight/internal/config }
  storage: { in: [cmd/insight/internal/storage, cmd/insight/internal/storage/**] }
  http: { in: cmd/insight/internal/http }
  events: { in: cmd/insight/internal/events }
  testutil: { in: cmd/insight/internal/testutil }
  research: { in: cmd/insight/internal/research }

deps:
  main:
    mayDependOn:
      - config
      - storage
      - http
      - research
  storage:
    mayDependOn:
      - storage
  http:
    mayDependOn:
      - events
      - research
  research:
    mayDependOn:
      - storage
  testutil:
    mayDependOn:
      - storage
