version: 3
workdir: .
allow:
  depOnAnyVendor: true
excludeFiles:
  - "^.*_test\\.go$"

components:
  main: { in: cmd/*/ }
  config: { in: cmd/*/internal/config }
  storage: { in: [cmd/*/internal/storage, cmd/*/internal/storage/**] }
  http: { in: cmd/*/internal/http }
  events: { in: cmd/*/internal/events }
  lib: { in: cmd/*/internal/lib/** }
  research: { in: [cmd/*/internal/research, cmd/*/internal/research/**] }

deps:
  main:
    mayDependOn:
      - config
      - storage
      - http
      - research
  storage:
    mayDependOn:
      - storage
  http:
    mayDependOn:
      - events
      - research
  research:
    mayDependOn:
      - research
      - storage
