// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Event struct {
	ID        string         `json:"id"`
	EventType string         `json:"event_type"`
	Received  string         `json:"received"`
	Payload   string         `json:"payload"`
	SessionID sql.NullString `json:"session_id"`
}
