// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Event struct {
	ID        string
	EventType string
	Received  string
	Payload   string
	SessionID sql.NullString
}
